spring:
  application:
    name: room

  datasource:
    url: jdbc:postgresql://localhost:5432/room
    username: admin
    password: Admin123@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | create-drop | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    server: http://localhost:8080
    title: My API Service
    version: 1.0.0

